apiVersion: v1
data:
  server.disable.auth: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"server.disable.auth":"true","server.insecure":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-11-14T15:33:57Z","labels":{"app.kubernetes.io/name":"argocd-cmd-params-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cmd-params-cm","namespace":"argocd","resourceVersion":"1493","uid":"381e3c8a-da29-42f8-860a-480e5094bdc3"}}
  creationTimestamp: "2022-11-14T15:33:57Z"
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "4188"
  uid: 381e3c8a-da29-42f8-860a-480e5094bdc3
